name: Build iOS Dictionary
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Xcode tools
        run: xcode-select --install
      - name: Build dictionary
        run: |
          mkdir -p ~/Desktop/OutputDict
          dictbuild -o ~/Desktop/OutputDict -i ./Index.xml -b ./Body.html -p ./Info.plist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-dictionary
          path: ~/Desktop/OutputDict/
